title: Berk Ozturk
description: Engineer, operations researcher, data scientist, tinkerer, motivated by the use of optimization in decision making.
theme: jekyll-theme-dinky

# Permalinks
permalink: /posts/:title